### 로그인 API
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "accountId": "admin",
  "password": "1234"
}

### 리프레쉬 토큰 API
POST http://localhost:8080/api/v1/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjQ0ODc2NjMsImV4cCI6MzMyNjA0ODc2NjMsInN1YiI6IkFjY2VzcyBUb2tlbiIsImlkIjoxLCJhY2NvdW50SWQiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiLtmY3quLjrj5kifQ.HAY5QufE5PwaZT__EOVF1WmuEIMU4pwLMCnor6wnSzU"
}

### 로그아웃 API
POST http://localhost:8080/api/v1/auth/logout
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjQ0ODc2NjMsImV4cCI6MzMyNjA0ODc2NjMsInN1YiI6IkFjY2VzcyBUb2tlbiIsImlkIjoxLCJhY2NvdW50SWQiOiJhZG1pbiIsInJvbGUiOiJBRE1JTiIsIm5hbWUiOiLtmY3quLjrj5kifQ.HAY5QufE5PwaZT__EOVF1WmuEIMU4pwLMCnor6wnSzU"
}
