### 로그인 API
POST http://localhost:8080/api/v1/auth/login
Content-Type: application/json

{
  "accountId": "admin",
  "password": "1234"
}

### 리프레쉬 토큰 API
POST http://localhost:8080/api/v1/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjQ0MzE2NDUsImV4cCI6MTgxMDgzMTY0NSwic3ViIjoiQWNjZXNzIFRva2VuIiwiaWQiOjEsImFjY291bnRJZCI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwibmFtZSI6Iu2Zjeq4uOuPmSJ9.mDOlJAkd0vijETK2STAmF_jp2DzDqDqdqdHWr91If44
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE3MjQ0MzMwMjcsImV4cCI6MTgxMDgzMzAyNywic3ViIjoiQWNjZXNzIFRva2VuIiwiaWQiOjEsImFjY291bnRJZCI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwibmFtZSI6Iu2Zjeq4uOuPmSJ9.ya6e4ZLJMyjNhZ5XHwRWSRX2RMKZrgwZaVRsLFBTpH8"
}

### 로그아웃 API
POST http://localhost:8080/api/v1/auth/logout
