FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY *.jar app.jar

ENV SPRING_PROFILES_ACTIVE=prod
ENV JASYPT_ENCRYPTOR_PASSWORD=$(./JASYPT_PASSWORD.sh)

ENTRYPOINT ["java", "-jar", "app.jar"]

EXPOSE 8080